# Site settings
title: New Directions
header-img: img/home-bg.jpg
email: newdirectionsphilmind@gmail.com
description: "New Directions in the Study of the Mind Project."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: studyofthemind
# github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Team names, titles and social links
people:
- name: Tim Crane
  pic: 1
  position: Principal Investigator
  social:
    - title: twitter
      url: https://twitter.com/timcrane102
    - title: flickr
      url: #
    - title: stack-overflow
      url: #

- name: Craig French
  pic: 2
  position: Postdoctoral Fellow
  social:
    - title: twitter
      url: https://twitter.com/EarlyModPhil
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Alex Grzankowski
  pic: 3
  position: Lecturer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Raamy Majeed
  pic: 4
  position: Postdoctoral Fellow
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Chris Meyns
  pic: 5
  position: Research Associate and Project Manager
  social:
    - title: twitter
      url: https://twitter.com/csmeyns
    - title: linkedin
      url: https://ca.linkedin.com/in/csmeyns  
